org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
# Unity Library properties
unityStreamingAssets=
unity.projectPath=/Users/ashupathak/Documents/Sagar/MusicPlayer/UnityGame
unity.androidSdkPath=/Applications/Unity/Hub/Editor/6000.5.1f1/PlaybackEngines/AndroidPlayer/SDK
unity.androidNdkPath=/Applications/Unity/Hub/Editor/6000.5.1f1/PlaybackEngines/AndroidPlayer/NDK
